config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  get 'index', to: 'articles#index'
  get 'articles/new', to: 'articles#new'
  get 'articles/:id', to: 'articles#show', as: :article
  get 'articles/:id/edit', to: 'articles#edit', as: :edit_article
  
  post 'articles', to: 'articles#create'
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy', as: :delete_article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
   
  def show
    @article = Article.find(params[:id])
  end
   
  def new
    @article = Article.new
  end
    
  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to index_path
  end
   
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to index_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Wikinimous", index_path, class: "navbar-brand" %>
    <form class="d-flex">
      <%= link_to "New Article", articles_new_path(@article) %>
    </form>
  </div>
</nav>

<div class="container d-flex justify-content-center">
  <div class="row">
    <div class="col-12 sm-col-12">
      <h1>Edit Article</h1>
        <%= form_for(@article) do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :content %>
        <%= f.text_field :content %>
        <%= f.submit(class: "btn btn-primary") %>
        <% end %>
      
    </div>
  </div>
</div>
    

app/views/articles/index.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Wikinimous", index_path, class: "navbar-brand" %>
    <form class="d-flex">
      <%= link_to "New Article", articles_new_path(@article) %>
    </form>
  </div>
</nav>

<div class="container d-flex justify-content-center">
  <div class="row justify-content-center">
    <div class="col-8 md-6">
      <ul>
        <% @articles.each do |article| %>
            <li class="list-group">
            <%= link_to article.title, article_path(article), class: "link-title" %>
            <p><%= article.content %></p>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
    

app/views/articles/new.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Wikinimous", index_path, class: "navbar-brand" %>
    <form class="d-flex">
      <%= link_to "New Article", articles_new_path(@article) %>
    </form>
  </div>
</nav>
<div class="container d-flex justify-content-center">
  <div class="row">
    <div class="col-12 sm-col-12">
      <h1>Create a New Article</h1>
        <%= form_for(@article) do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :content %>
        <%= f.text_field :content %>
        <%= f.submit(class: "btn btn-primary") %>
        <% end %>
      
    </div>
  </div>
</div>
    

app/views/articles/show.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Wikinimous", index_path, class: "navbar-brand" %>
    <form class="d-flex">
      <%= link_to "New Article", articles_new_path(@article) %>
    </form>
  </div>
</nav>

<div class="container d-flex justify-content-center">
  <div class="row justify-content-center">
    <div class="col-8 md-6">
      <div class="actions">
      <h1><%= @article.title %></h1>
        <%= link_to edit_article_path(@article) do %>
          <i class="fas fa-edit"></i>
        <% end %>
        
        <%= link_to delete_article_path(@article), method: :delete, data: {confirm: "Are you sure?"} do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
      <p><%= @article.content %><p>
    </div>
     <div class="link-back justify-content-end">
      <%= link_to "back to list", index_path %>
    </div>
  </div>
   
</div> 
    
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>